---
galaxy_info:
  author: "Jasper N. Brouwer, Ramon de la Fuente"
  description: Install latest PHP cli version in DotDeb repository
  company: Future500
  license: LGPL
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
      - wheezy
  categories:
    - web
    - system
dependencies:
  - f500.php
